version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/thret-clothing-web-ui"
    schedule:
      interval: "daily"
    assignees:
      - "rossyman"
    reviewers:
      - "rossyman"
    commit-message:
      prefix: "THRET-D"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rossyman"
    reviewers:
      - "rossyman"
    commit-message:
      prefix: "THRET-D"
      include: "scope"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rossyman"
    reviewers:
      - "rossyman"
    commit-message:
      prefix: "THRET-D"
      include: "scope"
