name: Hygiene Checks
on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  web_ui:
    name: UI Hygiene Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Cache node modules
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.npm
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-node-
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test:headless

      - name: Build SSR
        run: npm run build:ssr
